// <auto-generated />
using CrudEmploye.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrudEmploye.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241221221922_First Migration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CrudEmploye.Entities.Employee", b =>
                {
                    b.Property<int>("IdEmployee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmployee"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdProfile")
                        .HasColumnType("int");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("IdEmployee");

                    b.HasIndex("IdProfile");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("CrudEmploye.Entities.Profile", b =>
                {
                    b.Property<int>("IdProfile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProfile"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdProfile");

                    b.ToTable("Profile", (string)null);

                    b.HasData(
                        new
                        {
                            IdProfile = 1,
                            Name = "Programador JR"
                        },
                        new
                        {
                            IdProfile = 2,
                            Name = "Programador Dev"
                        },
                        new
                        {
                            IdProfile = 3,
                            Name = "Programador Senior"
                        },
                        new
                        {
                            IdProfile = 4,
                            Name = "Administrador SYS"
                        });
                });

            modelBuilder.Entity("CrudEmploye.Entities.Employee", b =>
                {
                    b.HasOne("CrudEmploye.Entities.Profile", "ReferenceProfile")
                        .WithMany("ReferenceEmployee")
                        .HasForeignKey("IdProfile")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReferenceProfile");
                });

            modelBuilder.Entity("CrudEmploye.Entities.Profile", b =>
                {
                    b.Navigation("ReferenceEmployee");
                });
#pragma warning restore 612, 618
        }
    }
}
